<?php
/**
 * Edupro SMS — School Database Seed
 * Run ONCE via CLI:  php portal/seed.php
 * Seeds all 10,147 Zimbabwe schools from the national registry.
 * Already-seeded schools are skipped (safe to re-run).
 */

require_once __DIR__ . '/db.php';

$schools = [
<?php // This array is generated by the Python build script below ?>
];

// ── Inline data — generated from School_Contacts_2021.xlsx ─────────────────
$data = getData();

$inserted = 0;
$skipped  = 0;

$stmt = db()->prepare("
    INSERT OR IGNORE INTO schools
        (school_name, school_level, province, district, mobile, phone, is_seeded, is_active, school_code, created_at)
    VALUES
        (:name, :level, :province, :district, :mobile, :phone, 1, 0, :code, datetime('now'))
");

foreach ($data as $s) {
    $stmt->execute([
        ':name'     => $s['name'],
        ':level'    => $s['level'],
        ':province' => $s['province'],
        ':district' => $s['district'],
        ':mobile'   => $s['cell'],
        ':phone'    => $s['phone'],
        ':code'     => generate_school_code(),
    ]);
    if (db()->lastInsertId()) $inserted++;
    else $skipped++;
}

// Also ensure modules rows exist for already-registered schools
$all = db()->query("SELECT id FROM schools WHERE is_active=1")->fetchAll();
foreach ($all as $school) {
    ensure_modules($school['id']);
}

echo "Seed complete. Inserted: $inserted | Skipped (already exist): $skipped\n";

function ensure_modules(int $school_id): void {
    foreach (MODULES as $code => $name) {
        db()->prepare("INSERT OR IGNORE INTO school_modules(school_id,module_code,module_name) VALUES(?,?,?)")
            ->execute([$school_id, $code, $name]);
    }
}

function getData(): array {
    return json_decode(file_get_contents(__DIR__ . '/data/schools_zw.json'), true) ?? [];
}
